#!/bin/sh

echo "Downloading..."
echo

#OFFICIAL
wget -O slsk.tgz http://www.soulseekqt.net/SoulseekQT/Linux/SoulseekQt-2015-6-25-64bit.tgz

#Icon hosted on my Dropbox
wget -O slsk.png https://www.dropbox.com/s/3qdatnoi10e3c17/slsk.png

tar xvzf ./slsk.tgz

su -c "install ./SoulseekQt-2015-6-25-64bit /usr/local/bin/slsk
install ./slsk.png /usr/share/pixmaps/slsk.png
install ./SoulseekQt.desktop /usr/share/applications/SoulseekQt.desktop
chmod +x /usr/local/bin/slsk
chmod +x /usr/share/pixmaps/slsk.png
chmod +x /usr/share/applications/SoulseekQt.desktop
ln -s /usr/share/applications/SoulseekQt.desktop ~/Desktop/SoulseekQt.desktop
"


echo "SoulseekQt 64bit is now installed"
echo "it can be found in the app menu or terminal slsk"
echo
echo "XVLVX - hails music lovers"
